[Interface]
PrivateKey = REDACTED
Address = 10.69.0.2/24
Table = off

PostUp = ip route add table 69 to 10.69.0.0/24 dev %i metric 100
PostUp = ip route add table 69 default via 10.69.0.1 dev %i metric 100
PostUp = ip rule add from 10.69.0.2 table 69 priority 69
PostUp = iptables -t nat -A POSTROUTING -s 192.168.30.0/24 -o %i -j MASQUERADE

PreDown = iptables -t nat -D POSTROUTING -s 192.168.30.0/24 -o %i -j MASQUERADE
PreDown = ip rule del from 10.69.0.2 table 69 priority 69
PreDown = ip route del table 69 to 10.69.0.0/24 dev %i metric 100
PreDown = ip route del table 69 default via 10.69.0.1 dev %i metric 100

[Peer]
PublicKey = REDACTED
AllowedIPs = 0.0.0.0/0
Endpoint = REDACTED
PersistentKeepalive = 25
